# Site settings
title: "Pooya Dowlatabadi"
description: "Pooya Dowlatabadi's resume

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Pooya Dowlatabadi"
resume_title:                   "SRE at ArvanCloud"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "pooyadowlat@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+98 935 557 5857"
resume_contact_address:         "Tehran, Iran"

resume_header_contact_info:     "Tehran, Iran • +98 935 557 5857 • pooyadowlat@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi I am Pooya, A happy SRE with 2+ years being SRE and I have been a freelance python developer before that, I like opensource, monitoring and being a Dataphile.My motto is monitor it like there is no tomorrow </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/itspooya"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/pooyadowlatabadi/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://pooyadowlatabadi.ir"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
